"""
Developable Deploy — phase 2 of the Backend Engineer pipeline.

Reads the .developable/config.json written by main.py, generates Terraform
IaC files, provisions cloud infrastructure, builds and pushes the Docker
image, and writes .github/workflows/deploy.yml.

Usage
─────
    python deploy.py --out ./output --deploy-to aws
    python deploy.py --out ./output --deploy-to gcp  --gcp-project my-project
    python deploy.py --out ./output --deploy-to heroku

All GitHub configuration is read from .developable/config.json when available.
Override any value with CLI flags.
"""

import argparse
import os
import sys
from pathlib import Path

from core.parser import PrismaParser
from core.project_config import ProjectConfig


def _push_terraform_to_github(out_dir: Path, provider: str) -> None:
    """
    Commit terraform/ and push to origin main if a GitHub remote exists.

    Runs after TerraformAgent.generate() so IaC files are version-controlled
    alongside the API code and CI can run terraform validate on them.
    Failures are non-fatal — a warning is printed and deployment continues.
    """
    import subprocess

    git_dir = out_dir / ".git"
    if not git_dir.exists():
        return

    # Check whether origin is configured
    remote = subprocess.run(
        ["git", "remote", "get-url", "origin"],
        cwd=out_dir, capture_output=True, text=True,
    )
    if remote.returncode != 0:
        print("  [Terraform] No git remote — skipping GitHub push of terraform/")
        return

    def git(*cmd: str) -> tuple[int, str]:
        r = subprocess.run(["git", *cmd], cwd=out_dir, capture_output=True, text=True)
        return r.returncode, (r.stdout + r.stderr).strip()

    git("add", "terraform/")

    # Skip commit if nothing staged (re-run with identical schema)
    rc, diff = git("diff", "--cached", "--quiet")
    if rc == 0:
        print("  [Terraform] terraform/ unchanged — nothing to push to GitHub")
        return

    rc, out = git(
        "commit", "-m",
        f"Add Terraform IaC files for {provider.upper()} deployment\n\n"
        "Generated by Developable deploy.py.",
    )
    if rc != 0:
        print(f"  [Terraform] Warning: git commit failed — {out}", file=__import__("sys").stderr)
        return

    print(f"  [Terraform] Pushing terraform/ to GitHub...")
    rc, out = git("push", "origin", "main")
    if rc != 0:
        print(
            f"  [Terraform] Warning: push failed — terraform/ is committed locally but not on GitHub.\n"
            f"  Push manually: cd {out_dir} && git push origin main\n"
            f"  ({out})",
            file=__import__("sys").stderr,
        )
        return

    print(f"  [Terraform] terraform/ pushed to GitHub ✓")


def _build_minimal_tf_provider_config(args: argparse.Namespace, provider: str) -> dict:
    if provider == "aws":
        return {"aws_region": getattr(args, "aws_region", None) or "us-east-1"}
    if provider == "gcp":
        return {
            "gcp_project": getattr(args, "gcp_project", None) or "",
            "gcp_region": getattr(args, "gcp_region", None) or "us-central1",
        }
    return {}  # Heroku: no provider-specific template vars needed


def main():
    parser = argparse.ArgumentParser(
        description="Developable Deploy — provision cloud infrastructure for a generated API"
    )
    parser.add_argument(
        "--out", default="./output",
        help="Output directory produced by main.py (default: ./output)",
    )
    parser.add_argument(
        "--deploy-to", required=True, metavar="PROVIDER",
        choices=["aws", "heroku", "gcp"],
        help="Cloud provider to deploy to: aws | heroku | gcp",
    )

    # ── Schema fallback ────────────────────────────────────────────────────────
    parser.add_argument(
        "--schema", default=None, metavar="PATH",
        help="Path to schema.prisma (resolved from config.json when omitted)",
    )

    # ── Provider-specific flags ────────────────────────────────────────────────
    parser.add_argument(
        "--aws-region", default=None, metavar="REGION",
        help="AWS region for ECS Fargate deployment (default: us-east-1)",
    )
    parser.add_argument(
        "--heroku-app", default=None, metavar="NAME",
        help="Heroku app name (default: <project-name>)",
    )
    parser.add_argument(
        "--gcp-project", default=None, metavar="PROJECT_ID",
        help="GCP project ID for Cloud Run deployment",
    )
    parser.add_argument(
        "--gcp-region", default=None, metavar="REGION",
        help="GCP region for Cloud Run deployment (default: us-central1)",
    )

    # ── GitHub overrides (fall back to config.json values) ────────────────────
    parser.add_argument(
        "--github-token", default=None, metavar="TOKEN",
        help="GitHub Personal Access Token (fallback: GITHUB_TOKEN env var or config.json)",
    )
    parser.add_argument(
        "--github-user", default=None, metavar="USER",
        help="GitHub username or org (fallback: config.json)",
    )
    parser.add_argument(
        "--github-repo", default=None, metavar="NAME",
        help="Repository name (fallback: config.json)",
    )

    args = parser.parse_args()

    out_dir = Path(args.out)
    if not out_dir.exists():
        print(f"Error: output directory {out_dir} not found. Run main.py first.", file=sys.stderr)
        sys.exit(1)

    # ── Load config written by main.py ─────────────────────────────────────────
    cfg = ProjectConfig(out_dir).load()

    # ── Resolve schema path ────────────────────────────────────────────────────
    schema_path: Path | None = None
    if args.schema:
        schema_path = Path(args.schema)
    elif cfg.get("schema_path"):
        schema_path = Path(cfg["schema_path"])
    else:
        candidate = out_dir / "schema.prisma"
        if candidate.exists():
            schema_path = candidate

    if schema_path is None or not schema_path.exists():
        print(
            f"Error: could not locate schema.prisma. "
            f"Pass --schema <path> or ensure main.py wrote .developable/config.json.",
            file=sys.stderr,
        )
        sys.exit(1)

    # ── Resolve tests_dir ──────────────────────────────────────────────────────
    tests_dir: Path | None = None
    if cfg.get("tests_dir"):
        candidate = Path(cfg["tests_dir"])
        if candidate.is_dir():
            tests_dir = candidate
    if tests_dir is None:
        candidate = out_dir / "tests"
        if candidate.is_dir():
            tests_dir = candidate

    # ── Resolve GitHub token (for Secrets API) ────────────────────────────────
    github_token = (
        args.github_token
        or os.environ.get("GITHUB_TOKEN", "")
        or cfg.get("github_user", "")  # token is not stored in config; env var is canonical
    )
    # Re-resolve cleanly: only CLI arg or env var supply the token; config holds user/repo.
    github_token = args.github_token or os.environ.get("GITHUB_TOKEN", "") or ""

    print(f"Parsing schema from {schema_path}...")
    spec = PrismaParser().parse(schema_path)

    # ── Resolved-config header ─────────────────────────────────────────────────
    project_name = spec["entities"][0]["name_lower"] + "-api" if spec.get("entities") else "unknown"
    config_source = f"{out_dir}/.developable/config.json" if cfg else "defaults only"
    if github_token:
        token_source = "✓  from --github-token flag" if args.github_token else "✓  from GITHUB_TOKEN env var"
    else:
        token_source = "✗  not set (deploy.yml secrets will need manual setup)"
    region_display = args.aws_region or "us-east-1 (default)"
    provider_detail = {
        "aws":    f"AWS   ({region_display})",
        "gcp":    f"GCP   ({args.gcp_project or 'project not set'} / {args.gcp_region or 'us-central1'})",
        "heroku": f"Heroku ({args.heroku_app or project_name})",
    }.get(args.deploy_to, args.deploy_to)

    _SEP = "─" * 58
    print(f"\n{_SEP}")
    print(f"  Developable Deploy")
    print(_SEP)
    print(f"  Entities       : {', '.join(e['name'] for e in spec['entities'])}")
    print(f"  Project        : {project_name}")
    print(f"  Output dir     : {out_dir.resolve()}")
    print(f"  Schema         : {schema_path}")
    print(f"  Provider       : {provider_detail}")
    print(f"  Tests dir      : {tests_dir or 'none detected'}")
    print(f"  GitHub token   : {token_source}")
    print(f"  Config source  : {config_source}")
    print(f"{_SEP}\n")

    # ── Terraform agent: generate IaC files ───────────────────────────────────
    from agents.terraform import TerraformAgent
    tf_config = _build_minimal_tf_provider_config(args, args.deploy_to)
    print(f"\n[Terraform] Generating IaC files for {args.deploy_to.upper()}...")
    TerraformAgent(out_dir, args.deploy_to, tf_config).generate(spec)
    print(f"  Terraform files written to {out_dir}/terraform/")

    # ── Commit + push terraform/ to GitHub ────────────────────────────────────
    # In the old single-command flow, terraform files were generated before
    # vc.publish() so they landed in the initial GitHub commit. Now that
    # deploy.py runs after main.py's push, we push them here as a follow-up
    # commit so the IaC is version-controlled and CI can run terraform validate.
    _push_terraform_to_github(out_dir, args.deploy_to)

    # ── Deployment agent: provision + deploy ──────────────────────────────────
    from agents.deployment import Deployment

    _eta_steps = {
        "aws": (
            "AWS deployment — estimated 20–25 min total",
            [
                ("Validate AWS credentials",                         "~5s"),
                ("Bootstrap S3 state bucket + DynamoDB lock table",  "~30s"),
                ("Provision 15 AWS resources via boto3",             "~10–15 min  ← longest step"),
                ("Build Docker image",                               "~3 min"),
                ("Push image to ECR",                                "~1 min"),
                ("Terraform import + reconciliation apply",          "~3 min"),
                ("Run Prisma migration (ECS task inside VPC)",       "~2 min"),
                ("Push deploy.yml + set GitHub Actions secrets",     "~30s"),
                ("Remote smoke tests",                               "~1 min"),
            ],
        ),
        "gcp": (
            "GCP deployment — estimated 15–20 min total",
            [
                ("Validate GCP credentials",                          "~5s"),
                ("Bootstrap GCS state bucket",                        "~30s"),
                ("Terraform apply — Cloud SQL + Cloud Run",           "~10 min  ← longest step"),
                ("Apply Prisma schema to Cloud SQL",                  "~1 min"),
                ("Build Docker image",                                "~3 min"),
                ("Push image to Artifact Registry",                   "~1 min"),
                ("Terraform apply (second pass — new Cloud Run rev)", "~1 min"),
                ("Push deploy.yml + set GitHub Actions secrets",      "~30s"),
                ("Remote smoke tests",                                "~1 min"),
            ],
        ),
        "heroku": (
            "Heroku deployment — estimated 6–10 min total",
            [
                ("Validate Heroku credentials",                      "~5s"),
                ("Terraform apply — app + Postgres addon",           "~2 min"),
                ("Apply Prisma schema to Heroku Postgres",           "~1 min"),
                ("Build Docker image",                               "~3 min"),
                ("Push image + release container",                   "~1 min"),
                ("Push deploy.yml + set GitHub Actions secrets",     "~30s"),
                ("Remote smoke tests",                               "~1 min"),
            ],
        ),
    }
    if args.deploy_to in _eta_steps:
        title, steps = _eta_steps[args.deploy_to]
        print(f"\n{'─' * 58}")
        print(f"  {title}")
        print(f"{'─' * 58}")
        for i, (label, eta) in enumerate(steps, 1):
            print(f"  {i:>2}. {label:<50} {eta}")
        print(f"{'─' * 58}\n")

    print(f"[Deployment] Deploying to {args.deploy_to.upper()}...")
    deployer = Deployment(
        out_dir=out_dir,
        provider=args.deploy_to,
        tests_dir=tests_dir,
        github_token=github_token,
        aws_region=args.aws_region,
        heroku_app=args.heroku_app,
        gcp_project=args.gcp_project,
        gcp_region=args.gcp_region,
    )
    record = deployer.deploy(spec, {})

    print(f"\n✓ Deployment complete!")
    print(f"  Endpoint : {record['endpoint']}")
    if record.get("region"):
        print(f"  Region   : {record['region']}")
    print(f"  Provider : {record['provider']}")
    print(f"  State    : {out_dir}/.developable/state.json")


if __name__ == "__main__":
    main()
