#!/usr/bin/env python3
"""
Comprehensive test script for the generated Blog API.

Tests all REST endpoints against the blog app schema (User, Post, Comment)
generated by Developable from test_schema.prisma.

Legend:
  🚀  Sending API request
  ✅  Test passed
  ❌  Test failed
  ⛔️  Auth / authorization issue detected
  ⚠️  Security warning

Usage:
  python test_blog_api.py [base_url]

  base_url defaults to $API_URL or http://localhost:3000
"""

import sys
import os
import json
import base64
import uuid
from typing import Any, Optional

try:
    import requests
except ImportError:
    print("Error: 'requests' is not installed. Run: pip install requests")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BASE_URL = (
    sys.argv[1] if len(sys.argv) > 1 else os.getenv("API_URL", "http://localhost:3000")
).rstrip("/")

# ---------------------------------------------------------------------------
# Counters & shared state
# ---------------------------------------------------------------------------

_results: list[dict] = []
_pass = 0
_fail = 0
_warn = 0


def _unique_email(prefix: str = "user") -> str:
    """Generate a unique email to avoid cross-run collisions."""
    return f"{prefix}_{uuid.uuid4().hex[:8]}@test.example.com"


# ---------------------------------------------------------------------------
# Logging helpers
# ---------------------------------------------------------------------------

def _section(title: str) -> None:
    print(f"\n{'═' * 64}")
    print(f"  {title}")
    print(f"{'═' * 64}")


def _log_ok(msg: str) -> None:
    global _pass
    _pass += 1
    print(f"  ✅  {msg}")


def _log_fail(msg: str) -> None:
    global _fail
    _fail += 1
    print(f"  ❌  {msg}")


def _log_auth(msg: str) -> None:
    """Log an auth/authz failure — counts as a test failure."""
    global _fail
    _fail += 1
    print(f"  ⛔️  {msg}")


def _log_warn(msg: str) -> None:
    """Log a security warning — does NOT count as a failure."""
    global _warn
    _warn += 1
    print(f"  ⚠️   {msg}")


# ---------------------------------------------------------------------------
# HTTP helpers
# ---------------------------------------------------------------------------

def _req(
    method: str,
    path: str,
    token: Optional[str] = None,
    body: Optional[dict] = None,
    params: Optional[dict] = None,
) -> requests.Response:
    headers: dict[str, str] = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    url = f"{BASE_URL}{path}"
    print(f"  🚀  {method.upper()} {path}")
    try:
        return requests.request(
            method,
            url,
            headers=headers,
            json=body,
            params=params,
            timeout=10,
        )
    except requests.exceptions.ConnectionError:
        print(f"\n  ❌  Cannot connect to {BASE_URL}. Is the API server running?")
        sys.exit(1)
    except requests.exceptions.Timeout:
        print(f"\n  ❌  Request to {path} timed out.")
        sys.exit(1)


def _assert_status(
    resp: requests.Response,
    expected: int,
    label: str,
    auth_fail: bool = False,
) -> bool:
    if resp.status_code == expected:
        _log_ok(f"{label} → HTTP {resp.status_code}")
        return True
    msg = (
        f"{label} → expected HTTP {expected}, got {resp.status_code}"
        f" | body: {resp.text[:300]}"
    )
    if auth_fail:
        _log_auth(msg)
    else:
        _log_fail(msg)
    return False


def _assert_field(
    data: dict,
    field: str,
    label: str,
    absent: bool = False,
) -> bool:
    if absent:
        if field in data:
            _log_fail(f"{label}: field '{field}' should NOT be present but was found")
            return False
        _log_ok(f"{label}: field '{field}' correctly absent")
        return True
    if field in data:
        _log_ok(f"{label}: field '{field}' present")
        return True
    _log_fail(f"{label}: field '{field}' missing from response")
    return False


def _assert_paginated(data: dict, label: str) -> bool:
    ok = True
    if "data" not in data:
        _log_fail(f"{label}: missing 'data' array")
        ok = False
    if "meta" not in data:
        _log_fail(f"{label}: missing 'meta' object")
        ok = False
    if not ok:
        return False
    meta = data["meta"]
    for key in ("total", "page", "limit", "totalPages", "hasNext", "hasPrev"):
        if key not in meta:
            _log_fail(f"{label}: meta missing key '{key}'")
            ok = False
    if ok:
        _log_ok(
            f"{label}: paginated response — total={meta['total']} "
            f"page={meta['page']}/{meta['totalPages']}"
        )
    return ok


def _decode_jwt(token: str) -> Optional[dict]:
    try:
        payload_b64 = token.split(".")[1]
        padding = 4 - len(payload_b64) % 4
        if padding != 4:
            payload_b64 += "=" * padding
        return json.loads(base64.urlsafe_b64decode(payload_b64))
    except Exception:
        return None


def _no_password_in(obj: Any, context: str = "response") -> bool:
    """Recursively verify 'password' does not appear in any response field."""
    if isinstance(obj, dict):
        if "password" in obj:
            _log_warn(f"'password' field is EXPOSED in {context}")
            return False
        return all(_no_password_in(v, context) for v in obj.values())
    if isinstance(obj, list):
        return all(_no_password_in(item, context) for item in obj)
    return True


def _safe_json(resp: requests.Response) -> dict:
    try:
        return resp.json()
    except Exception:
        return {}


# ---------------------------------------------------------------------------
# Main test suite
# ---------------------------------------------------------------------------

def run_all_tests() -> None:
    # Unique email seeds to avoid inter-run collisions
    email1 = _unique_email("alice")
    email2 = _unique_email("bob")
    email3 = _unique_email("charlie")

    state: dict[str, Any] = {}

    # -----------------------------------------------------------------------
    _section("0 · HEALTH CHECK")
    # -----------------------------------------------------------------------

    resp = _req("GET", "/health")
    if _assert_status(resp, 200, "GET /health"):
        data = _safe_json(resp)
        if data.get("status") == "ok":
            _log_ok("Health check body contains status=ok")
        else:
            _log_fail(f"Health check body unexpected: {data}")

    # -----------------------------------------------------------------------
    _section("1 · AUTH — REGISTER")
    # -----------------------------------------------------------------------

    # 1-1  Valid registration for user 1
    resp = _req("POST", "/auth/register", body={
        "email": email1, "password": "SecurePass1!", "name": "Alice Tester"
    })
    if _assert_status(resp, 201, "Register user1 (valid)"):
        data = _safe_json(resp)
        _assert_field(data, "token", "Register user1")
        _assert_field(data, "user", "Register user1")
        if "user" in data:
            _assert_field(data["user"], "id", "Register user1.user")
            _assert_field(data["user"], "email", "Register user1.user")
            # Security: password must NOT appear in response
            if not _no_password_in(data, "register response"):
                _log_warn("Password field leaked in /auth/register response body")
            else:
                _log_ok("Password is NOT present in register response body")
        state["user1_token"] = data.get("token", "")
        state["user1_id"] = data.get("user", {}).get("id")
        # Security: JWT payload must not contain password
        payload = _decode_jwt(state["user1_token"])
        if payload is not None:
            if "password" in payload:
                _log_warn("JWT payload contains 'password' field — tokens are readable!")
            else:
                _log_ok("JWT payload does NOT contain 'password' field")

    # 1-2  Valid registration for user 2
    resp = _req("POST", "/auth/register", body={
        "email": email2, "password": "AnotherPass9#", "name": "Bob Reviewer"
    })
    if _assert_status(resp, 201, "Register user2 (valid)"):
        data = _safe_json(resp)
        state["user2_token"] = data.get("token", "")
        state["user2_id"] = data.get("user", {}).get("id")
        _log_ok(f"user2 registered with id={state['user2_id']}")

    # 1-3  Valid registration for user 3 (used then deleted)
    resp = _req("POST", "/auth/register", body={
        "email": email3, "password": "TempUser!7x", "name": "Charlie Temp"
    })
    if _assert_status(resp, 201, "Register user3 (valid)"):
        data = _safe_json(resp)
        state["user3_token"] = data.get("token", "")
        state["user3_id"] = data.get("user", {}).get("id")

    # 1-4  Duplicate email → 409
    resp = _req("POST", "/auth/register", body={
        "email": email1, "password": "SecurePass1!", "name": "Alice Duplicate"
    })
    _assert_status(resp, 409, "Register duplicate email → 409")

    # 1-5  Missing email → 400
    resp = _req("POST", "/auth/register", body={
        "password": "SecurePass1!", "name": "No Email"
    })
    _assert_status(resp, 400, "Register without email → 400")

    # 1-6  Missing password → 400
    resp = _req("POST", "/auth/register", body={
        "email": _unique_email("no_pw"), "name": "No Password"
    })
    _assert_status(resp, 400, "Register without password → 400")

    # 1-7  Missing name → 400
    resp = _req("POST", "/auth/register", body={
        "email": _unique_email("no_name"), "password": "SecurePass1!"
    })
    _assert_status(resp, 400, "Register without name → 400")

    # 1-8  Invalid email format → 400
    resp = _req("POST", "/auth/register", body={
        "email": "not-an-email", "password": "SecurePass1!", "name": "Bad Email"
    })
    _assert_status(resp, 400, "Register with invalid email format → 400")

    # 1-9  Password too short (<8 chars) → 400
    resp = _req("POST", "/auth/register", body={
        "email": _unique_email("short_pw"), "password": "1234567", "name": "Short Pass"
    })
    _assert_status(resp, 400, "Register with password <8 chars → 400")

    # 1-10  Empty password string → 400
    resp = _req("POST", "/auth/register", body={
        "email": _unique_email("empty_pw"), "password": "", "name": "Empty Pass"
    })
    _assert_status(resp, 400, "Register with empty password → 400")

    # 1-11  Empty body → 400
    resp = _req("POST", "/auth/register", body={})
    _assert_status(resp, 400, "Register with empty body → 400")

    # 1-12  Bio field is optional — should succeed
    resp = _req("POST", "/auth/register", body={
        "email": _unique_email("bio_user"),
        "password": "WithBio!99",
        "name": "Bio User",
        "bio": "I write tests for fun.",
    })
    if _assert_status(resp, 201, "Register with optional 'bio' field"):
        data = _safe_json(resp)
        if data.get("user", {}).get("bio") == "I write tests for fun.":
            _log_ok("Bio field persisted correctly")
        else:
            _log_fail("Bio field not returned in register response")

    # 1-13  Extra unknown fields should be ignored (not cause 500)
    resp = _req("POST", "/auth/register", body={
        "email": _unique_email("extra"),
        "password": "ExtraFields1!",
        "name": "Extra Fields",
        "role": "admin",          # unknown — should be stripped
        "isAdmin": True,          # unknown — should be stripped
    })
    _assert_status(resp, 201, "Register with extra/unknown fields → 201 (ignored)")

    # -----------------------------------------------------------------------
    _section("2 · AUTH — LOGIN")
    # -----------------------------------------------------------------------

    # 2-1  Valid login
    resp = _req("POST", "/auth/login", body={"email": email1, "password": "SecurePass1!"})
    if _assert_status(resp, 200, "Login user1 (valid credentials)"):
        data = _safe_json(resp)
        _assert_field(data, "token", "Login response")
        # Security: password must NOT be in login response
        if not _no_password_in(data, "login response"):
            _log_warn("Password field leaked in /auth/login response")
        else:
            _log_ok("Password NOT present in login response")
        # Refresh token in state
        if "token" in data:
            state["user1_token"] = data["token"]

    # 2-2  Wrong password → 401
    resp = _req("POST", "/auth/login", body={"email": email1, "password": "WrongPass!!"})
    _assert_status(resp, 401, "Login with wrong password → 401", auth_fail=True)

    # 2-3  Non-existent user → 401
    resp = _req("POST", "/auth/login", body={
        "email": _unique_email("ghost"), "password": "SecurePass1!"
    })
    _assert_status(resp, 401, "Login with non-existent email → 401", auth_fail=True)

    # 2-4  Missing email → 400
    resp = _req("POST", "/auth/login", body={"password": "SecurePass1!"})
    _assert_status(resp, 400, "Login without email → 400")

    # 2-5  Missing password → 400
    resp = _req("POST", "/auth/login", body={"email": email1})
    _assert_status(resp, 400, "Login without password → 400")

    # 2-6  Empty body → 400
    resp = _req("POST", "/auth/login", body={})
    _assert_status(resp, 400, "Login with empty body → 400")

    # 2-7  Invalid email format → 400
    resp = _req("POST", "/auth/login", body={"email": "bad@@email", "password": "SecurePass1!"})
    _assert_status(resp, 400, "Login with malformed email → 400")

    # 2-8  Correct email, empty password string → 400 or 401
    resp = _req("POST", "/auth/login", body={"email": email1, "password": ""})
    if resp.status_code not in (400, 401):
        _log_fail(f"Login with empty password string → expected 400/401, got {resp.status_code}")
    else:
        _log_ok(f"Login with empty password string → HTTP {resp.status_code}")

    # -----------------------------------------------------------------------
    _section("3 · USERS — GET (unauthenticated reads)")
    # -----------------------------------------------------------------------

    # 3-1  List users — paginated
    resp = _req("GET", "/api/users")
    if _assert_status(resp, 200, "GET /api/users"):
        _assert_paginated(_safe_json(resp), "GET /api/users")
        data = _safe_json(resp)
        # Security: no password in list response
        if not _no_password_in(data.get("data", []), "GET /api/users list"):
            _log_warn("Password field exposed in GET /api/users list response")
        else:
            _log_ok("Password field absent from all user records in list")

    # 3-2  Pagination params — page & limit
    resp = _req("GET", "/api/users", params={"page": 1, "limit": 1})
    if _assert_status(resp, 200, "GET /api/users?page=1&limit=1"):
        meta = _safe_json(resp).get("meta", {})
        if meta.get("limit") == 1:
            _log_ok("Pagination limit=1 respected")
        else:
            _log_fail(f"Expected limit=1 in meta, got {meta.get('limit')}")

    # 3-3  Page=0 is normalised to 1 (parsePagination uses Math.max(1, ...))
    resp = _req("GET", "/api/users", params={"page": 0})
    if _assert_status(resp, 200, "GET /api/users?page=0 → normalised to page 1"):
        meta = _safe_json(resp).get("meta", {})
        if meta.get("page", 0) >= 1:
            _log_ok(f"page=0 normalised to page={meta.get('page')}")
        else:
            _log_fail(f"page=0 not normalised correctly: {meta}")

    # 3-4  Limit > 100 is capped at 100
    resp = _req("GET", "/api/users", params={"limit": 9999})
    if _assert_status(resp, 200, "GET /api/users?limit=9999 → capped at 100"):
        meta = _safe_json(resp).get("meta", {})
        if meta.get("limit", 0) <= 100:
            _log_ok(f"limit capped at {meta.get('limit')}")
        else:
            _log_fail(f"limit not capped: meta.limit={meta.get('limit')}")

    # 3-5  Very high page → empty data list
    resp = _req("GET", "/api/users", params={"page": 99999})
    if _assert_status(resp, 200, "GET /api/users?page=99999 → empty data"):
        data = _safe_json(resp).get("data", None)
        if isinstance(data, list) and len(data) == 0:
            _log_ok("High page number returns empty data array")
        elif data is not None:
            _log_fail(f"Expected empty data array, got {len(data)} items")

    # 3-6  Get user by ID
    user1_id = state.get("user1_id")
    if user1_id:
        resp = _req("GET", f"/api/users/{user1_id}")
        if _assert_status(resp, 200, f"GET /api/users/{user1_id} (valid)"):
            data = _safe_json(resp)
            if data.get("id") == user1_id:
                _log_ok("User id matches requested id")
            else:
                _log_fail(f"User id mismatch: expected {user1_id}, got {data.get('id')}")
            # Security: no password in single-user response
            if not _no_password_in(data, f"GET /api/users/{user1_id}"):
                _log_warn(f"Password field exposed in single-user response")
            else:
                _log_ok("Password field absent from single user response")

    # 3-7  Non-existent user → 404
    resp = _req("GET", "/api/users/9999999")
    _assert_status(resp, 404, "GET /api/users/9999999 → 404")

    # 3-8  Non-numeric ID → 400
    resp = _req("GET", "/api/users/abc")
    _assert_status(resp, 400, "GET /api/users/abc → 400 (invalid ID)")

    # 3-9  Negative ID → 404 or 400
    resp = _req("GET", "/api/users/-1")
    if resp.status_code in (400, 404):
        _log_ok(f"GET /api/users/-1 → HTTP {resp.status_code} (acceptable)")
    else:
        _log_fail(f"GET /api/users/-1 → unexpected HTTP {resp.status_code}")

    # 3-10  Floating-point ID → 400
    resp = _req("GET", "/api/users/1.5")
    if resp.status_code in (400, 404):
        _log_ok(f"GET /api/users/1.5 → HTTP {resp.status_code} (invalid ID handled)")
    else:
        _log_fail(f"GET /api/users/1.5 → unexpected HTTP {resp.status_code}")

    # -----------------------------------------------------------------------
    _section("4 · USERS — WRITE OPERATIONS (auth required)")
    # -----------------------------------------------------------------------

    # 4-1  POST /api/users without token → 401
    resp = _req("POST", "/api/users", body={
        "email": _unique_email("anon"), "password": "NoToken!1", "name": "Anon"
    })
    _assert_status(resp, 401, "POST /api/users without auth → 401", auth_fail=True)

    # 4-2  PUT /api/users/:id without token → 401
    if user1_id:
        resp = _req("PUT", f"/api/users/{user1_id}", body={"name": "No Token Edit"})
        _assert_status(resp, 401, f"PUT /api/users/{user1_id} without auth → 401", auth_fail=True)

    # 4-3  DELETE /api/users/:id without token → 401
    if user1_id:
        resp = _req("DELETE", f"/api/users/{user1_id}")
        _assert_status(resp, 401, f"DELETE /api/users/{user1_id} without auth → 401", auth_fail=True)

    # 4-4  POST /api/users with valid auth
    resp = _req("POST", "/api/users", token=state.get("user1_token"), body={
        "email": _unique_email("created_by_api"),
        "password": "Created!123",
        "name": "API Created User",
    })
    if _assert_status(resp, 201, "POST /api/users with valid auth → 201"):
        state["api_created_user_id"] = _safe_json(resp).get("id")

    # 4-5  PUT /api/users/:id with valid auth — update own name
    if user1_id and state.get("user1_token"):
        resp = _req("PUT", f"/api/users/{user1_id}", token=state["user1_token"],
                    body={"name": "Alice Updated"})
        if _assert_status(resp, 200, f"PUT /api/users/{user1_id} with auth → 200"):
            data = _safe_json(resp)
            if data.get("name") == "Alice Updated":
                _log_ok("Name update persisted correctly")
            else:
                _log_fail(f"Name not updated: got {data.get('name')!r}")
            if not _no_password_in(data, "PUT /api/users response"):
                _log_warn("Password exposed in PUT /api/users response")

    # 4-6  Security warning: any authenticated user can modify ANY user (no ownership check)
    user2_id = state.get("user2_id")
    if user1_id and user2_id and state.get("user2_token"):
        resp = _req("PUT", f"/api/users/{user1_id}", token=state["user2_token"],
                    body={"bio": "Hijacked by user2"})
        if resp.status_code == 200:
            _log_warn(
                f"SECURITY: user2 (id={user2_id}) can update user1 (id={user1_id})'s profile "
                "because the User entity has no ownership check. Consider adding ownership "
                "guards to PUT/DELETE /api/users/:id."
            )
        elif resp.status_code == 403:
            _log_ok("PUT /api/users/:id by non-owner correctly returns 403")

    # 4-7  PUT /api/users/:id — non-existent user → 404
    if state.get("user1_token"):
        resp = _req("PUT", "/api/users/9999999", token=state["user1_token"],
                    body={"name": "Ghost"})
        _assert_status(resp, 404, "PUT /api/users/9999999 (non-existent) → 404")

    # 4-8  DELETE /api/users/:id with valid auth (delete the temporarily created user)
    api_created = state.get("api_created_user_id")
    if api_created and state.get("user1_token"):
        resp = _req("DELETE", f"/api/users/{api_created}", token=state["user1_token"])
        _assert_status(resp, 204, f"DELETE /api/users/{api_created} → 204")

    # -----------------------------------------------------------------------
    _section("5 · POSTS — GET (unauthenticated reads)")
    # -----------------------------------------------------------------------

    # Pre-seed: create posts as user1 and user2 to have data for GETs
    post_body_1 = {"title": "Hello World from Alice", "content": "My first post content."}
    post_body_2 = {"title": "Alice Second Post", "content": "Second post by Alice.", "published": True}
    post_body_user2 = {"title": "Bob's Post", "content": "Content by Bob the reviewer."}

    resp = _req("POST", "/api/posts", token=state.get("user1_token"), body=post_body_1)
    if _assert_status(resp, 201, "Seed: Create post1 for user1"):
        data = _safe_json(resp)
        state["post1_id"] = data.get("id")
        # Verify authorId injected correctly
        if data.get("authorId") == state.get("user1_id"):
            _log_ok("authorId correctly injected from JWT token (not from body)")
        else:
            _log_fail(
                f"authorId mismatch: expected {state.get('user1_id')}, got {data.get('authorId')}"
            )

    resp = _req("POST", "/api/posts", token=state.get("user1_token"), body=post_body_2)
    if _assert_status(resp, 201, "Seed: Create post2 for user1"):
        state["post2_id"] = _safe_json(resp).get("id")

    resp = _req("POST", "/api/posts", token=state.get("user2_token"), body=post_body_user2)
    if _assert_status(resp, 201, "Seed: Create post3 for user2"):
        state["post3_id"] = _safe_json(resp).get("id")

    # 5-1  GET /api/posts → paginated
    resp = _req("GET", "/api/posts")
    if _assert_status(resp, 200, "GET /api/posts → 200"):
        data = _safe_json(resp)
        _assert_paginated(data, "GET /api/posts")

    # 5-2  Pagination: limit=1, page=2
    resp = _req("GET", "/api/posts", params={"limit": 1, "page": 2})
    if _assert_status(resp, 200, "GET /api/posts?limit=1&page=2"):
        data = _safe_json(resp)
        meta = data.get("meta", {})
        if meta.get("page") == 2 and meta.get("limit") == 1:
            _log_ok("Pagination page=2 limit=1 meta is correct")
        else:
            _log_fail(f"Unexpected meta: {meta}")
        if meta.get("hasPrev") is True:
            _log_ok("meta.hasPrev=true on page 2")
        else:
            _log_fail(f"Expected hasPrev=true on page 2, got {meta.get('hasPrev')}")

    # 5-3  GET /api/posts/:id → 200
    post1_id = state.get("post1_id")
    if post1_id:
        resp = _req("GET", f"/api/posts/{post1_id}")
        if _assert_status(resp, 200, f"GET /api/posts/{post1_id} → 200"):
            data = _safe_json(resp)
            if data.get("id") == post1_id:
                _log_ok("Post id matches")
            else:
                _log_fail(f"Post id mismatch: {data.get('id')} vs {post1_id}")

    # 5-4  GET /api/posts/9999999 → 404
    resp = _req("GET", "/api/posts/9999999")
    _assert_status(resp, 404, "GET /api/posts/9999999 → 404")

    # 5-5  GET /api/posts/notanid → 400
    resp = _req("GET", "/api/posts/notanid")
    _assert_status(resp, 400, "GET /api/posts/notanid → 400 (invalid ID)")

    # -----------------------------------------------------------------------
    _section("6 · POSTS — WRITE OPERATIONS")
    # -----------------------------------------------------------------------

    # 6-1  POST /api/posts without auth → 401
    resp = _req("POST", "/api/posts", body={"title": "Anon Post", "content": "Anon content"})
    _assert_status(resp, 401, "POST /api/posts without auth → 401", auth_fail=True)

    # 6-2  POST /api/posts with auth but missing title → 400
    resp = _req("POST", "/api/posts", token=state.get("user1_token"),
                body={"content": "No title here"})
    _assert_status(resp, 400, "POST /api/posts missing title → 400")

    # 6-3  POST /api/posts with auth but missing content → 400
    resp = _req("POST", "/api/posts", token=state.get("user1_token"),
                body={"title": "Title Only"})
    _assert_status(resp, 400, "POST /api/posts missing content → 400")

    # 6-4  POST /api/posts with empty body → 400
    resp = _req("POST", "/api/posts", token=state.get("user1_token"), body={})
    _assert_status(resp, 400, "POST /api/posts empty body → 400")

    # 6-5  POST /api/posts — attempt to spoof authorId in body (must be overridden)
    user2_id = state.get("user2_id")
    if user1_id and user2_id and state.get("user1_token"):
        resp = _req("POST", "/api/posts", token=state["user1_token"], body={
            "title": "Spoof Test", "content": "Trying to set authorId to user2",
            "authorId": user2_id,  # should be ignored / overridden
        })
        if _assert_status(resp, 201, "POST /api/posts with spoofed authorId → 201"):
            data = _safe_json(resp)
            if data.get("authorId") == user1_id:
                _log_ok(
                    "authorId spoofing prevented: injected from token, not from body"
                )
            elif data.get("authorId") == user2_id:
                _log_warn(
                    "SECURITY: authorId spoofing succeeded! "
                    "User1 created a post attributed to user2. "
                    "The controller should always override authorId from req.user.id."
                )
            state["spoofed_post_id"] = data.get("id")

    # 6-6  PUT /api/posts/:id without auth → 401
    if post1_id:
        resp = _req("PUT", f"/api/posts/{post1_id}", body={"title": "Anon Edit"})
        _assert_status(resp, 401, f"PUT /api/posts/{post1_id} without auth → 401", auth_fail=True)

    # 6-7  PUT /api/posts/:id with owner token → 200
    if post1_id and state.get("user1_token"):
        resp = _req("PUT", f"/api/posts/{post1_id}", token=state["user1_token"],
                    body={"title": "Updated Title by Alice"})
        if _assert_status(resp, 200, f"PUT /api/posts/{post1_id} by owner → 200"):
            data = _safe_json(resp)
            if data.get("title") == "Updated Title by Alice":
                _log_ok("Title update persisted")
            else:
                _log_fail(f"Title not updated: {data.get('title')!r}")

    # 6-8  PUT /api/posts/:id with non-owner token → 403
    if post1_id and state.get("user2_token"):
        resp = _req("PUT", f"/api/posts/{post1_id}", token=state["user2_token"],
                    body={"title": "Hijack by Bob"})
        _assert_status(resp, 403, f"PUT /api/posts/{post1_id} by non-owner → 403",
                       auth_fail=True)

    # 6-9  PUT /api/posts/9999999 with owner token → 404
    if state.get("user1_token"):
        resp = _req("PUT", "/api/posts/9999999", token=state["user1_token"],
                    body={"title": "Ghost Update"})
        _assert_status(resp, 404, "PUT /api/posts/9999999 (non-existent) → 404")

    # 6-10  PUT /api/posts/:id with invalid data → 400
    if post1_id and state.get("user1_token"):
        resp = _req("PUT", f"/api/posts/{post1_id}", token=state["user1_token"],
                    body={"title": ""})
        if resp.status_code in (400, 200):
            if resp.status_code == 400:
                _log_ok("PUT /api/posts with empty title → 400 (validation)")
            else:
                _log_warn(
                    "PUT /api/posts with empty string title returned 200 — "
                    "consider adding min-length validation in the Zod schema"
                )

    # 6-11  DELETE /api/posts/:id without auth → 401
    post2_id = state.get("post2_id")
    if post2_id:
        resp = _req("DELETE", f"/api/posts/{post2_id}")
        _assert_status(resp, 401, f"DELETE /api/posts/{post2_id} without auth → 401",
                       auth_fail=True)

    # 6-12  DELETE /api/posts/:id with non-owner → 403
    if post2_id and state.get("user2_token"):
        resp = _req("DELETE", f"/api/posts/{post2_id}", token=state["user2_token"])
        _assert_status(resp, 403, f"DELETE /api/posts/{post2_id} by non-owner → 403",
                       auth_fail=True)

    # 6-13  DELETE /api/posts/:id with owner → 204
    if post2_id and state.get("user1_token"):
        resp = _req("DELETE", f"/api/posts/{post2_id}", token=state["user1_token"])
        if _assert_status(resp, 204, f"DELETE /api/posts/{post2_id} by owner → 204"):
            state["post2_deleted"] = True

    # 6-14  GET after delete → 404
    if post2_id and state.get("post2_deleted"):
        resp = _req("GET", f"/api/posts/{post2_id}")
        _assert_status(resp, 404, f"GET /api/posts/{post2_id} after deletion → 404")

    # 6-15  DELETE /api/posts/9999999 → 404
    if state.get("user1_token"):
        resp = _req("DELETE", "/api/posts/9999999", token=state["user1_token"])
        _assert_status(resp, 404, "DELETE /api/posts/9999999 (non-existent) → 404")

    # -----------------------------------------------------------------------
    _section("7 · COMMENTS — GET (unauthenticated reads)")
    # -----------------------------------------------------------------------

    # Pre-seed: create a comment as user1 on post1
    post1_id = state.get("post1_id")
    if post1_id and state.get("user1_token"):
        resp = _req("POST", "/api/comments", token=state["user1_token"],
                    body={"body": "Great article, Alice!", "postId": post1_id})
        if _assert_status(resp, 201, "Seed: Create comment1 by user1 on post1"):
            data = _safe_json(resp)
            state["comment1_id"] = data.get("id")
            if data.get("authorId") == user1_id:
                _log_ok("authorId correctly injected from token for POST /api/comments")
            else:
                _log_fail(f"authorId mismatch: {data.get('authorId')} vs {user1_id}")
            if data.get("postId") == post1_id:
                _log_ok("postId from body correctly stored")
            else:
                _log_fail(f"postId mismatch: {data.get('postId')} vs {post1_id}")

    # Create a second comment by user2 on post1
    if post1_id and state.get("user2_token"):
        resp = _req("POST", "/api/comments", token=state["user2_token"],
                    body={"body": "Interesting perspective!", "postId": post1_id})
        if _assert_status(resp, 201, "Seed: Create comment2 by user2 on post1"):
            state["comment2_id"] = _safe_json(resp).get("id")

    # 7-1  GET /api/comments → paginated
    resp = _req("GET", "/api/comments")
    if _assert_status(resp, 200, "GET /api/comments → 200"):
        _assert_paginated(_safe_json(resp), "GET /api/comments")

    # 7-2  GET /api/comments/:id → 200
    comment1_id = state.get("comment1_id")
    if comment1_id:
        resp = _req("GET", f"/api/comments/{comment1_id}")
        if _assert_status(resp, 200, f"GET /api/comments/{comment1_id} → 200"):
            data = _safe_json(resp)
            if data.get("id") == comment1_id:
                _log_ok("Comment id matches")

    # 7-3  GET /api/comments/9999999 → 404
    resp = _req("GET", "/api/comments/9999999")
    _assert_status(resp, 404, "GET /api/comments/9999999 → 404")

    # 7-4  GET /api/comments/bad → 400
    resp = _req("GET", "/api/comments/bad")
    _assert_status(resp, 400, "GET /api/comments/bad → 400")

    # -----------------------------------------------------------------------
    _section("8 · COMMENTS — WRITE OPERATIONS")
    # -----------------------------------------------------------------------

    # 8-1  POST /api/comments without auth → 401
    if post1_id:
        resp = _req("POST", "/api/comments", body={"body": "Anonymous comment", "postId": post1_id})
        _assert_status(resp, 401, "POST /api/comments without auth → 401", auth_fail=True)

    # 8-2  POST /api/comments — missing body field → 400
    if post1_id and state.get("user1_token"):
        resp = _req("POST", "/api/comments", token=state["user1_token"],
                    body={"postId": post1_id})
        _assert_status(resp, 400, "POST /api/comments missing 'body' → 400")

    # 8-3  POST /api/comments — missing postId → 400
    if state.get("user1_token"):
        resp = _req("POST", "/api/comments", token=state["user1_token"],
                    body={"body": "No postId"})
        _assert_status(resp, 400, "POST /api/comments missing 'postId' → 400")

    # 8-4  POST /api/comments — invalid postId (non-existent) → 400 or 500 (FK violation)
    if state.get("user1_token"):
        resp = _req("POST", "/api/comments", token=state["user1_token"],
                    body={"body": "Ghost post comment", "postId": 9999999})
        if resp.status_code in (400, 404, 422, 409, 500):
            _log_ok(
                f"POST /api/comments with non-existent postId → HTTP {resp.status_code} "
                "(DB referential integrity enforced)"
            )
        else:
            _log_fail(
                f"POST /api/comments with non-existent postId → unexpected HTTP {resp.status_code}"
            )

    # 8-5  PUT /api/comments/:id without auth → 401
    comment1_id = state.get("comment1_id")
    if comment1_id:
        resp = _req("PUT", f"/api/comments/{comment1_id}", body={"body": "Anon edit"})
        _assert_status(resp, 401, f"PUT /api/comments/{comment1_id} without auth → 401",
                       auth_fail=True)

    # 8-6  PUT /api/comments/:id with owner → 200
    if comment1_id and state.get("user1_token"):
        resp = _req("PUT", f"/api/comments/{comment1_id}", token=state["user1_token"],
                    body={"body": "Edited comment by Alice"})
        if _assert_status(resp, 200, f"PUT /api/comments/{comment1_id} by owner → 200"):
            data = _safe_json(resp)
            if data.get("body") == "Edited comment by Alice":
                _log_ok("Comment body update persisted")
            else:
                _log_fail(f"Comment body not updated: {data.get('body')!r}")

    # 8-7  PUT /api/comments/:id with non-owner → 403
    if comment1_id and state.get("user2_token"):
        resp = _req("PUT", f"/api/comments/{comment1_id}", token=state["user2_token"],
                    body={"body": "Bob steals Alice comment"})
        _assert_status(resp, 403, f"PUT /api/comments/{comment1_id} by non-owner → 403",
                       auth_fail=True)

    # 8-8  DELETE /api/comments/:id without auth → 401
    comment2_id = state.get("comment2_id")
    if comment2_id:
        resp = _req("DELETE", f"/api/comments/{comment2_id}")
        _assert_status(resp, 401, f"DELETE /api/comments/{comment2_id} without auth → 401",
                       auth_fail=True)

    # 8-9  DELETE /api/comments/:id with non-owner → 403
    if comment2_id and state.get("user1_token"):
        resp = _req("DELETE", f"/api/comments/{comment2_id}", token=state["user1_token"])
        _assert_status(resp, 403, f"DELETE /api/comments/{comment2_id} by non-owner → 403",
                       auth_fail=True)

    # 8-10  DELETE /api/comments/:id with owner → 204
    if comment2_id and state.get("user2_token"):
        resp = _req("DELETE", f"/api/comments/{comment2_id}", token=state["user2_token"])
        if _assert_status(resp, 204, f"DELETE /api/comments/{comment2_id} by owner → 204"):
            state["comment2_deleted"] = True

    # 8-11  GET deleted comment → 404
    if comment2_id and state.get("comment2_deleted"):
        resp = _req("GET", f"/api/comments/{comment2_id}")
        _assert_status(resp, 404, f"GET /api/comments/{comment2_id} after deletion → 404")

    # 8-12  DELETE /api/comments/9999999 → 404
    if state.get("user1_token"):
        resp = _req("DELETE", "/api/comments/9999999", token=state["user1_token"])
        _assert_status(resp, 404, "DELETE /api/comments/9999999 (non-existent) → 404")

    # -----------------------------------------------------------------------
    _section("9 · NESTED ROUTES — GET /api/users/:id/posts & /comments")
    # -----------------------------------------------------------------------

    # 9-1  GET /api/users/:id/posts → 200 paginated, only user's posts
    if user1_id:
        resp = _req("GET", f"/api/users/{user1_id}/posts")
        if _assert_status(resp, 200, f"GET /api/users/{user1_id}/posts → 200"):
            data = _safe_json(resp)
            _assert_paginated(data, f"GET /api/users/{user1_id}/posts")
            posts = data.get("data", [])
            wrong_author = [p for p in posts if p.get("authorId") != user1_id]
            if wrong_author:
                _log_fail(
                    f"GET /api/users/{user1_id}/posts returned posts with wrong authorId: "
                    f"{[p['authorId'] for p in wrong_author]}"
                )
            else:
                _log_ok(f"All posts in /api/users/{user1_id}/posts belong to user1")

    # 9-2  GET /api/users/:id/posts for non-existent user → empty paginated list
    resp = _req("GET", "/api/users/9999999/posts")
    if _assert_status(resp, 200, "GET /api/users/9999999/posts → 200 (empty)"):
        data = _safe_json(resp)
        if data.get("meta", {}).get("total", -1) == 0:
            _log_ok("Non-existent user's posts returns empty data with total=0")

    # 9-3  GET /api/users/:id/comments → 200 paginated, only user's comments
    if user1_id:
        resp = _req("GET", f"/api/users/{user1_id}/comments")
        if _assert_status(resp, 200, f"GET /api/users/{user1_id}/comments → 200"):
            data = _safe_json(resp)
            _assert_paginated(data, f"GET /api/users/{user1_id}/comments")
            comments = data.get("data", [])
            wrong_author = [c for c in comments if c.get("authorId") != user1_id]
            if wrong_author:
                _log_fail(f"Comments list contains items from other users")
            else:
                _log_ok(f"All comments in /api/users/{user1_id}/comments belong to user1")

    # -----------------------------------------------------------------------
    _section("10 · NESTED ROUTES — POST /api/users/posts (auth entity, token-based)")
    # -----------------------------------------------------------------------

    # 10-1  POST /api/users/posts without auth → 401
    resp = _req("POST", "/api/users/posts", body={"title": "Anon via user route", "content": "."})
    _assert_status(resp, 401, "POST /api/users/posts without auth → 401", auth_fail=True)

    # 10-2  POST /api/users/posts with auth → 201, authorId from token
    if state.get("user1_token"):
        resp = _req("POST", "/api/users/posts", token=state["user1_token"],
                    body={"title": "Post via user-nested route", "content": "This is the content."})
        if _assert_status(resp, 201, "POST /api/users/posts with auth → 201"):
            data = _safe_json(resp)
            if data.get("authorId") == user1_id:
                _log_ok("authorId set from token (not URL param) on user-nested POST")
            else:
                _log_fail(f"authorId mismatch on user-nested POST: {data.get('authorId')}")
            state["user_nested_post_id"] = data.get("id")

    # 10-3  PUT /api/users/posts/:childId with token owner → 200
    nested_post_id = state.get("user_nested_post_id")
    if nested_post_id and state.get("user1_token"):
        resp = _req("PUT", f"/api/users/posts/{nested_post_id}", token=state["user1_token"],
                    body={"title": "Updated via user-nested route"})
        if _assert_status(resp, 200, f"PUT /api/users/posts/{nested_post_id} by owner → 200"):
            data = _safe_json(resp)
            if data.get("title") == "Updated via user-nested route":
                _log_ok("Update via user-nested PUT persisted correctly")

    # 10-4  PUT /api/users/posts/:childId with different user token → 404
    #       (controller checks existing.authorId !== token.id → AppError 404)
    if nested_post_id and state.get("user2_token"):
        resp = _req("PUT", f"/api/users/posts/{nested_post_id}", token=state["user2_token"],
                    body={"title": "Bob hijacks user-nested post"})
        if resp.status_code in (403, 404):
            _log_ok(
                f"PUT /api/users/posts/{nested_post_id} by non-owner → "
                f"HTTP {resp.status_code} (correct)"
            )
        else:
            _log_auth(
                f"PUT /api/users/posts/{nested_post_id} by non-owner → "
                f"unexpected HTTP {resp.status_code}"
            )

    # 10-5  DELETE /api/users/posts/:childId without auth → 401
    if nested_post_id:
        resp = _req("DELETE", f"/api/users/posts/{nested_post_id}")
        _assert_status(resp, 401, f"DELETE /api/users/posts/{nested_post_id} without auth → 401",
                       auth_fail=True)

    # 10-6  DELETE /api/users/posts/:childId with owner token → 204
    if nested_post_id and state.get("user1_token"):
        resp = _req("DELETE", f"/api/users/posts/{nested_post_id}", token=state["user1_token"])
        _assert_status(resp, 204, f"DELETE /api/users/posts/{nested_post_id} by owner → 204")

    # -----------------------------------------------------------------------
    _section("11 · NESTED ROUTES — POST /api/users/comments")
    # -----------------------------------------------------------------------

    # 11-1  POST /api/users/comments without auth → 401
    if post1_id:
        resp = _req("POST", "/api/users/comments", body={"body": "Anon via user", "postId": post1_id})
        _assert_status(resp, 401, "POST /api/users/comments without auth → 401", auth_fail=True)

    # 11-2  POST /api/users/comments — missing postId → 400
    if state.get("user1_token"):
        resp = _req("POST", "/api/users/comments", token=state["user1_token"],
                    body={"body": "No postId here"})
        _assert_status(resp, 400, "POST /api/users/comments missing postId → 400")

    # 11-3  POST /api/users/comments with auth → 201, authorId from token
    if post1_id and state.get("user1_token"):
        resp = _req("POST", "/api/users/comments", token=state["user1_token"],
                    body={"body": "Comment via user-nested route", "postId": post1_id})
        if _assert_status(resp, 201, "POST /api/users/comments with auth → 201"):
            data = _safe_json(resp)
            if data.get("authorId") == user1_id:
                _log_ok("authorId set from token on user-nested comment POST")
            else:
                _log_fail(f"authorId mismatch: {data.get('authorId')} vs {user1_id}")
            state["user_nested_comment_id"] = data.get("id")

    # 11-4  PUT /api/users/comments/:childId by owner → 200
    nested_comment_id = state.get("user_nested_comment_id")
    if nested_comment_id and state.get("user1_token"):
        resp = _req("PUT", f"/api/users/comments/{nested_comment_id}", token=state["user1_token"],
                    body={"body": "Edited via user-nested comment route"})
        if _assert_status(resp, 200, f"PUT /api/users/comments/{nested_comment_id} by owner → 200"):
            data = _safe_json(resp)
            if data.get("body") == "Edited via user-nested comment route":
                _log_ok("Update via user-nested PUT persisted correctly")

    # 11-5  PUT /api/users/comments/:childId by different user → 403/404
    if nested_comment_id and state.get("user2_token"):
        resp = _req("PUT", f"/api/users/comments/{nested_comment_id}", token=state["user2_token"],
                    body={"body": "Bob hijacks comment"})
        if resp.status_code in (403, 404):
            _log_ok(
                f"PUT /api/users/comments/{nested_comment_id} by non-owner → "
                f"HTTP {resp.status_code}"
            )
        else:
            _log_auth(
                f"PUT /api/users/comments/{nested_comment_id} by non-owner → "
                f"unexpected HTTP {resp.status_code}"
            )

    # 11-6  DELETE /api/users/comments/:childId by owner → 204
    if nested_comment_id and state.get("user1_token"):
        resp = _req("DELETE", f"/api/users/comments/{nested_comment_id}", token=state["user1_token"])
        _assert_status(resp, 204, f"DELETE /api/users/comments/{nested_comment_id} → 204")

    # -----------------------------------------------------------------------
    _section("12 · NESTED ROUTES — /api/posts/:id/comments")
    # -----------------------------------------------------------------------

    post1_id = state.get("post1_id")
    post3_id = state.get("post3_id")

    # 12-1  GET /api/posts/:id/comments → 200 paginated, only comments for that post
    if post1_id:
        resp = _req("GET", f"/api/posts/{post1_id}/comments")
        if _assert_status(resp, 200, f"GET /api/posts/{post1_id}/comments → 200"):
            data = _safe_json(resp)
            _assert_paginated(data, f"GET /api/posts/{post1_id}/comments")
            comments = data.get("data", [])
            wrong_post = [c for c in comments if c.get("postId") != post1_id]
            if wrong_post:
                _log_fail(f"Comments list contains items from other posts: {wrong_post}")
            else:
                _log_ok(f"All comments correctly scoped to post {post1_id}")

    # 12-2  GET /api/posts/9999999/comments → 200 empty
    resp = _req("GET", "/api/posts/9999999/comments")
    if _assert_status(resp, 200, "GET /api/posts/9999999/comments → 200 (empty)"):
        meta = _safe_json(resp).get("meta", {})
        if meta.get("total", -1) == 0:
            _log_ok("Non-existent post's comments returns total=0")

    # 12-3  POST /api/posts/:id/comments without auth → 401
    if post1_id:
        resp = _req("POST", f"/api/posts/{post1_id}/comments",
                    body={"body": "Anonymous comment on post"})
        _assert_status(resp, 401,
                       f"POST /api/posts/{post1_id}/comments without auth → 401",
                       auth_fail=True)

    # 12-4  POST /api/posts/:id/comments with auth → 201, postId injected from URL
    if post1_id and state.get("user1_token"):
        resp = _req("POST", f"/api/posts/{post1_id}/comments", token=state["user1_token"],
                    body={"body": "Comment via post-nested route", "authorId": user1_id})
        if _assert_status(resp, 201, f"POST /api/posts/{post1_id}/comments → 201"):
            data = _safe_json(resp)
            if data.get("postId") == post1_id:
                _log_ok("postId correctly injected from URL (not from body)")
            else:
                _log_fail(f"postId mismatch: {data.get('postId')} vs {post1_id}")
            state["post_nested_comment_id"] = data.get("id")

    # 12-5  Security: authorId can be set to any value via post-nested route
    if post1_id and state.get("user1_token") and user2_id:
        resp = _req("POST", f"/api/posts/{post1_id}/comments", token=state["user1_token"],
                    body={"body": "Claimed as user2", "authorId": user2_id})
        if resp.status_code == 201:
            data = _safe_json(resp)
            if data.get("authorId") == user2_id:
                _log_warn(
                    f"SECURITY: POST /api/posts/:id/comments allows arbitrary authorId — "
                    f"user1 (id={user1_id}) created a comment attributed to user2 (id={user2_id}). "
                    "The nested-post comment route should inject authorId from req.user.id."
                )
                state["spoofed_comment_id"] = data.get("id")
            elif data.get("authorId") == user1_id:
                _log_ok(
                    "POST /api/posts/:id/comments: authorId correctly set from token "
                    "(spoof attempt ignored)"
                )

    # 12-6  PUT /api/posts/:id/comments/:childId with auth → 200
    post_nested_comment_id = state.get("post_nested_comment_id")
    if post1_id and post_nested_comment_id and state.get("user1_token"):
        resp = _req("PUT", f"/api/posts/{post1_id}/comments/{post_nested_comment_id}",
                    token=state["user1_token"], body={"body": "Updated comment body"})
        if _assert_status(resp, 200,
                          f"PUT /api/posts/{post1_id}/comments/{post_nested_comment_id} → 200"):
            data = _safe_json(resp)
            if data.get("body") == "Updated comment body":
                _log_ok("Comment update persisted via post-nested route")

    # 12-7  PUT /api/posts/:id/comments/:childId — wrong post parent → 404
    if post3_id and post_nested_comment_id and state.get("user1_token"):
        resp = _req("PUT", f"/api/posts/{post3_id}/comments/{post_nested_comment_id}",
                    token=state["user1_token"], body={"body": "Wrong parent"})
        _assert_status(resp, 404,
                       f"PUT /api/posts/{post3_id}/comments/{post_nested_comment_id} "
                       "(wrong parent) → 404")

    # 12-8  DELETE /api/posts/:id/comments/:childId without auth → 401
    if post1_id and post_nested_comment_id:
        resp = _req("DELETE", f"/api/posts/{post1_id}/comments/{post_nested_comment_id}")
        _assert_status(resp, 401,
                       f"DELETE /api/posts/{post1_id}/comments/{post_nested_comment_id} "
                       "without auth → 401",
                       auth_fail=True)

    # 12-9  DELETE /api/posts/:id/comments/:childId with auth → 204
    if post1_id and post_nested_comment_id and state.get("user1_token"):
        resp = _req("DELETE", f"/api/posts/{post1_id}/comments/{post_nested_comment_id}",
                    token=state["user1_token"])
        _assert_status(resp, 204,
                       f"DELETE /api/posts/{post1_id}/comments/{post_nested_comment_id} → 204")

    # -----------------------------------------------------------------------
    _section("13 · TOKEN EDGE CASES & SECURITY")
    # -----------------------------------------------------------------------

    # 13-1  Malformed token → 401
    if post1_id:
        resp = _req("PUT", f"/api/posts/{post1_id}", token="not.a.valid.jwt",
                    body={"title": "Malformed token attempt"})
        _assert_status(resp, 401, "Request with malformed JWT → 401", auth_fail=True)

    # 13-2  Tampered token (flip one byte in signature) → 401
    raw_token = state.get("user1_token", "")
    if raw_token and raw_token.count(".") == 2:
        parts = raw_token.split(".")
        sig = parts[2]
        tampered_sig = sig[:-1] + ("A" if sig[-1] != "A" else "B")
        tampered_token = ".".join(parts[:2] + [tampered_sig])
        if post1_id:
            resp = _req("PUT", f"/api/posts/{post1_id}", token=tampered_token,
                        body={"title": "Tampered token"})
            _assert_status(resp, 401, "Request with tampered JWT signature → 401",
                           auth_fail=True)

    # 13-3  Empty Bearer token → 401
    if post1_id:
        resp = _req("PUT", f"/api/posts/{post1_id}", token="",
                    body={"title": "Empty token"})
        _assert_status(resp, 401, "Request with empty token string → 401", auth_fail=True)

    # 13-4  Authorization header without "Bearer" prefix → 401
    if post1_id and raw_token:
        headers = {
            "Content-Type": "application/json",
            "Authorization": raw_token,  # Missing "Bearer " prefix
        }
        url = f"{BASE_URL}/api/posts/{post1_id}"
        print(f"  🚀  PUT /api/posts/{post1_id} (Auth without 'Bearer' prefix)")
        resp = requests.put(url, headers=headers, json={"title": "No bearer prefix"}, timeout=10)
        if resp.status_code == 401:
            _log_ok("Missing 'Bearer' prefix in Authorization header → 401")
        else:
            _log_warn(
                f"Authorization header without 'Bearer' prefix returned HTTP {resp.status_code} "
                "— ensure middleware requires the 'Bearer' scheme"
            )

    # -----------------------------------------------------------------------
    _section("14 · INPUT VALIDATION & EDGE CASES")
    # -----------------------------------------------------------------------

    # 14-1  Very long title (> 255 chars) — should be rejected or truncated
    long_title = "A" * 300
    if state.get("user1_token"):
        resp = _req("POST", "/api/posts", token=state["user1_token"],
                    body={"title": long_title, "content": "Some content"})
        if resp.status_code in (400, 422):
            _log_ok(f"POST /api/posts with title length=300 → HTTP {resp.status_code} (rejected)")
        elif resp.status_code == 201:
            _log_warn(
                "POST /api/posts with 300-char title accepted — consider adding "
                "max-length validation (e.g. .max(255)) in the Zod schema for 'title'"
            )
            state["long_title_post_id"] = _safe_json(resp).get("id")

    # 14-2  Very long content (> 10,000 chars)
    long_content = "C" * 15_000
    if state.get("user1_token"):
        resp = _req("POST", "/api/posts", token=state["user1_token"],
                    body={"title": "Long Content Test", "content": long_content})
        if resp.status_code in (400, 422):
            _log_ok(f"POST /api/posts with content length=15000 → HTTP {resp.status_code}")
        elif resp.status_code == 201:
            _log_warn(
                "POST /api/posts accepted 15,000-char content — "
                "consider .max(10000) in the Zod content schema"
            )
            state["long_content_post_id"] = _safe_json(resp).get("id")

    # 14-3  XSS payload in content — should be stored as-is (escaping at render layer)
    xss_payload = '<script>alert("xss")</script>'
    if state.get("user1_token"):
        resp = _req("POST", "/api/posts", token=state["user1_token"],
                    body={"title": "XSS Test Post", "content": xss_payload})
        if resp.status_code == 201:
            data = _safe_json(resp)
            stored_content = data.get("content", "")
            if stored_content == xss_payload:
                _log_warn(
                    "XSS payload stored verbatim in the database. Ensure HTML escaping is "
                    "applied when content is rendered in a browser context."
                )
                _log_ok("API stored content without modification (escaping responsibility of frontend)")
            state["xss_post_id"] = data.get("id")
        else:
            _log_ok(f"XSS payload in content rejected with HTTP {resp.status_code}")

    # 14-4  SQL injection attempt in query param
    resp = _req("GET", "/api/posts", params={"page": "1; DROP TABLE posts; --"})
    if resp.status_code == 200:
        _log_ok("SQL injection attempt in ?page param → server handled gracefully (200)")
    elif resp.status_code == 400:
        _log_ok("SQL injection attempt in ?page param → 400 (rejected)")
    else:
        _log_warn(f"SQL injection in page param → unexpected HTTP {resp.status_code}")

    # 14-5  Null bytes in string fields
    if state.get("user1_token"):
        resp = _req("POST", "/api/posts", token=state["user1_token"],
                    body={"title": "Null\x00Byte", "content": "Content\x00here"})
        if resp.status_code in (400, 201):
            _log_ok(f"Null byte in string fields → HTTP {resp.status_code} (handled)")
        else:
            _log_warn(f"Null byte in string fields → HTTP {resp.status_code}")

    # 14-6  Unicode / emoji in content
    if state.get("user1_token"):
        resp = _req("POST", "/api/posts", token=state["user1_token"],
                    body={"title": "Unicode Test 🌍", "content": "Emoji content: 🚀✅❌⚠️"})
        if _assert_status(resp, 201, "POST /api/posts with Unicode/emoji content → 201"):
            data = _safe_json(resp)
            if "🚀" in data.get("content", ""):
                _log_ok("Unicode/emoji stored and returned correctly")
            state["unicode_post_id"] = data.get("id")

    # 14-7  Numeric string as ID  (e.g. " 1 " with whitespace)
    if user1_id:
        resp = _req("GET", f"/api/users/ {user1_id} ")
        # Express router may strip whitespace or treat it as a different segment
        if resp.status_code in (400, 404):
            _log_ok(f"GET /api/users/' {user1_id} ' (whitespace padding) → HTTP {resp.status_code}")
        else:
            _log_warn(f"GET with whitespace in ID param → HTTP {resp.status_code}")

    # 14-8  Empty title string (explicit "")
    if state.get("user1_token"):
        resp = _req("POST", "/api/posts", token=state["user1_token"],
                    body={"title": "", "content": "Content with empty title"})
        if resp.status_code == 400:
            _log_ok("POST /api/posts with empty string title → 400 (validation)")
        elif resp.status_code == 201:
            _log_warn(
                "POST /api/posts accepted empty string title. "
                "Consider .min(1) in the Zod 'title' schema."
            )

    # 14-9  Pagination with non-numeric params → defaults applied
    resp = _req("GET", "/api/posts", params={"page": "abc", "limit": "xyz"})
    if _assert_status(resp, 200, "GET /api/posts?page=abc&limit=xyz → defaults to page=1 limit=20"):
        meta = _safe_json(resp).get("meta", {})
        if meta.get("page") == 1 and meta.get("limit") == 20:
            _log_ok("Non-numeric pagination params fallback to defaults page=1 limit=20")
        else:
            _log_warn(f"Non-numeric pagination produced unexpected meta: {meta}")

    # -----------------------------------------------------------------------
    _section("15 · RESPONSE STRUCTURE INTEGRITY")
    # -----------------------------------------------------------------------

    # 15-1  Error responses use { "error": "..." } format
    resp = _req("GET", "/api/posts/9999999")
    if resp.status_code == 404:
        data = _safe_json(resp)
        if "error" in data:
            _log_ok("Error response uses { error: '...' } format (404)")
        else:
            _log_fail(f"Error response missing 'error' key: {data}")

    # 15-2  Validation error response also uses { "error": "..." }
    resp = _req("POST", "/api/posts", token=state.get("user1_token"), body={})
    if resp.status_code == 400:
        data = _safe_json(resp)
        if "error" in data:
            _log_ok("Validation error response uses { error: '...' } format (400)")
        else:
            _log_fail(f"Validation error response missing 'error' key: {data}")

    # 15-3  201 Created response includes the created resource
    if state.get("user1_token") and post1_id:
        resp = _req("POST", "/api/comments", token=state["user1_token"],
                    body={"body": "Structure check comment", "postId": post1_id})
        if _assert_status(resp, 201, "POST /api/comments → 201 with resource body"):
            data = _safe_json(resp)
            for field in ("id", "body", "authorId", "postId"):
                _assert_field(data, field, f"POST /api/comments response.{field}")
            state["structure_check_comment_id"] = data.get("id")

    # 15-4  204 No Content response has empty body
    sc_comment = state.get("structure_check_comment_id")
    if sc_comment and state.get("user1_token"):
        resp = _req("DELETE", f"/api/comments/{sc_comment}", token=state["user1_token"])
        if _assert_status(resp, 204, f"DELETE /api/comments/{sc_comment} → 204"):
            if len(resp.content) == 0:
                _log_ok("204 response correctly has no body")
            else:
                _log_warn(f"204 response has non-empty body: {resp.text[:100]}")

    # 15-5  All paginated list endpoints include 'meta.hasNext' and 'meta.hasPrev'
    for endpoint in ("/api/users", "/api/posts", "/api/comments"):
        resp = _req("GET", endpoint)
        if resp.status_code == 200:
            meta = _safe_json(resp).get("meta", {})
            if "hasNext" in meta and "hasPrev" in meta:
                _log_ok(f"GET {endpoint}: meta.hasNext and meta.hasPrev present")
            else:
                _log_fail(f"GET {endpoint}: meta missing hasNext/hasPrev — got {meta}")

    # -----------------------------------------------------------------------
    _section("16 · SECURITY — SENSITIVE FIELDS AUDIT")
    # -----------------------------------------------------------------------

    # Collect all endpoints that return user data and ensure no password is leaked
    endpoints_to_check = [
        ("GET", "/api/users"),
        ("GET", f"/api/users/{user1_id}" if user1_id else None),
    ]

    for method, path in endpoints_to_check:
        if not path:
            continue
        resp = _req(method, path)
        if resp.status_code == 200:
            data = _safe_json(resp)
            # For list, check data array; for single, check object
            items = data.get("data", [data]) if "data" in data else [data]
            for item in items:
                if "password" in item:
                    _log_warn(
                        f"SECURITY: 'password' field is EXPOSED in {method} {path} response. "
                        "This is a critical data leak. Ensure safeSelect excludes the password "
                        "field from all read queries."
                    )
                    break
            else:
                _log_ok(f"'password' field absent from all records in {method} {path}")

    # Check JWT payload
    token_to_check = state.get("user1_token", "")
    if token_to_check:
        payload = _decode_jwt(token_to_check)
        if payload:
            if "password" in payload:
                _log_warn(
                    "SECURITY: JWT payload contains 'password' field. "
                    "Tokens can be decoded by anyone and should never carry sensitive credentials."
                )
            else:
                _log_ok("JWT payload does NOT contain 'password' field")
            # Warn if JWT has no expiry
            if "exp" not in payload:
                _log_warn("JWT payload has no 'exp' claim — tokens never expire!")
            else:
                _log_ok(f"JWT has 'exp' claim (expires at {payload['exp']})")

    # Audit: register response must not contain password
    audit_email = _unique_email("audit")
    resp = _req("POST", "/auth/register", body={
        "email": audit_email, "password": "AuditPass!1", "name": "Audit User"
    })
    if resp.status_code == 201:
        raw = resp.text
        if "AuditPass!1" in raw:
            _log_warn(
                "SECURITY CRITICAL: Plaintext password 'AuditPass!1' appears in register response!"
            )
        elif '"password"' in raw:
            _log_warn("SECURITY: 'password' key present in register response JSON")
        else:
            _log_ok("Plaintext password does NOT appear anywhere in register response body")

    # -----------------------------------------------------------------------
    _section("17 · CLEANUP — Delete remaining test data")
    # -----------------------------------------------------------------------

    # Clean up in reverse dependency order: comments → posts → (users optional)
    cleanup_comments = [
        state.get("comment1_id"),
        state.get("spoofed_comment_id"),
    ]
    for cid in cleanup_comments:
        if cid and state.get("user1_token"):
            resp = _req("DELETE", f"/api/comments/{cid}", token=state["user1_token"])
            if resp.status_code in (204, 404):
                _log_ok(f"Cleanup: comment {cid} removed (HTTP {resp.status_code})")
            else:
                _log_warn(f"Cleanup: comment {cid} → unexpected HTTP {resp.status_code}")

    cleanup_posts = [
        state.get("post1_id"),
        state.get("post3_id"),
        state.get("spoofed_post_id"),
        state.get("long_title_post_id"),
        state.get("long_content_post_id"),
        state.get("xss_post_id"),
        state.get("unicode_post_id"),
    ]
    for pid in cleanup_posts:
        if not pid:
            continue
        # Determine which token to use based on which user created it
        token = state.get("user1_token")
        if pid == state.get("post3_id"):
            token = state.get("user2_token")
        if token:
            resp = _req("DELETE", f"/api/posts/{pid}", token=token)
            if resp.status_code in (204, 404, 403):
                _log_ok(f"Cleanup: post {pid} removed/handled (HTTP {resp.status_code})")
            else:
                _log_warn(f"Cleanup: post {pid} → unexpected HTTP {resp.status_code}")

    # -----------------------------------------------------------------------
    # Final summary
    # -----------------------------------------------------------------------

    total = _pass + _fail
    print(f"\n{'═' * 64}")
    print(f"  TEST SUMMARY")
    print(f"{'═' * 64}")
    print(f"  ✅  Passed  : {_pass}")
    print(f"  ❌  Failed  : {_fail}")
    print(f"  ⚠️   Warnings: {_warn}")
    print(f"  Total tests : {total}")
    print(f"{'═' * 64}")

    if _fail > 0:
        print(f"\n  {_fail} test(s) FAILED. Review the ❌ entries above.")
        sys.exit(1)
    else:
        print(f"\n  All {total} tests passed!")
        if _warn > 0:
            print(f"  Review the {_warn} ⚠️  security warnings above.")


if __name__ == "__main__":
    print(f"  Blog API Test Suite")
    print(f"  Target: {BASE_URL}")
    run_all_tests()
