"""
Translates a skill config dict into a Developable CLI invocation string.

This is the single source of truth for how skill config maps to main.py flags.
GitHub and deploy flags are intentionally excluded — the skill handles those
steps directly in Phase 3; infra files are always generated by main.py now.

CLI usage (reads JSON from stdin, prints the command):
    echo '{"schema_path": "./prisma/schema.prisma", "out_dir": "./output"}' | python core/command_builder.py
"""
import json
import sys


def build_cli_command(config: dict) -> str:
    """
    Build a main.py CLI invocation from a skill config dict.

    Required keys:
        schema_path  (str)

    Optional keys:
        cli          (str)   CLI binary — default "python main.py"
        out_dir      (str)   default "./output"
        tests_out    (str)   if set, appends --tests-out <value>
        no_llm       (bool)  default True (skill fills LLM sections in Phase 2)
        rules        (str)   path to .rules.yaml, appended if provided
        force        (bool)  default False
    """
    schema_path = config.get("schema_path")
    if not schema_path:
        raise ValueError("schema_path is required")

    cli = config.get("cli", "python main.py")
    parts = [cli, str(schema_path)]

    out_dir = config.get("out_dir", "./output")
    parts += ["--out", str(out_dir)]

    if config.get("no_llm", True):
        parts.append("--no-llm")

    tests_out = config.get("tests_out")
    if tests_out:
        parts += ["--tests-out", str(tests_out)]

    rules = config.get("rules")
    if rules:
        parts += ["--rules", str(rules)]

    if config.get("force", False):
        parts.append("--force")

    return " ".join(parts)


if __name__ == "__main__":
    raw = sys.stdin.read().strip()
    try:
        config = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(f"Error: invalid JSON — {exc}", file=sys.stderr)
        sys.exit(1)
    print(build_cli_command(config))
