import subprocess
import sys
from pathlib import Path
from typing import Any

import requests

from core.vc_planner import VCPlanner
from core.assembler import Assembler

GITIGNORE_CONTENT = """\
# Dependencies
node_modules/

# Build output
dist/

# Environment — never commit secrets
.env

# TypeScript build info
*.tsbuildinfo
*.js.map

# OS
.DS_Store
Thumbs.db

# Logs
*.log
npm-debug.log*

# Prisma generated client (regenerated on install)
prisma/generated/
"""


class VersionControl:
    """
    The Version Control agent.

    Responsible for:
    1. Generating CI/CD infrastructure files (Dockerfile, docker-compose.yml,
       GitHub Actions workflow) into the output directory.
    2. Initialising a git repository and creating an initial commit.
    3. Creating a new GitHub repository via the REST API.
    4. Pushing the main branch to GitHub.

    Follows the same Planner → Assembler pattern as Developer and Tester.
    """

    def __init__(
        self,
        out_dir: Path,
        github_token: str,
        github_user: str,
        repo_name: str,
        private: bool = False,
    ):
        self.out_dir = out_dir
        self.github_token = github_token
        self.github_user = github_user
        self.repo_name = repo_name
        self.private = private
        self.assembler = Assembler(out_dir=out_dir, use_llm=False)

    def publish(self, spec: dict[str, Any], api_plan: dict[str, Any]) -> str:
        """
        Generate infra files, init git, create GitHub repo, push.

        Args:
            spec:     Parsed Prisma spec from PrismaParser.
            api_plan: File plan returned by the Developer agent.

        Returns:
            The HTML URL of the created GitHub repository.
        """
        self._spec = spec  # stored for entity-specific repo description
        print("  Generating infrastructure files (Dockerfile, docker-compose, CI)...")
        self._generate_infra_files(spec)

        print("  Writing .gitignore...")
        self._write_gitignore()

        print("  Initialising git repository...")
        self._init_git()

        print(f"  Creating GitHub repository '{self.github_user}/{self.repo_name}'...")
        repo_html_url, clone_url = self._create_github_repo()

        print(f"  Pushing to {repo_html_url} ...")
        self._push_to_github(clone_url)

        return repo_html_url

    # ── Private helpers ────────────────────────────────────────────────────────

    def _generate_infra_files(self, spec: dict[str, Any]) -> None:
        plan = VCPlanner().plan(spec)
        print(f"  Planned {len(plan['files'])} infrastructure files")
        self.assembler.assemble(spec, plan)

    def _write_gitignore(self) -> None:
        (self.out_dir / ".gitignore").write_text(GITIGNORE_CONTENT)

    def _init_git(self) -> None:
        self._git("init")
        self._git("add", ".")
        self._git(
            "commit", "-m",
            "Initial commit: Generated by Developable\n\n"
            "API, tests, Dockerfile, docker-compose, and GitHub Actions CI.",
        )
        self._git("branch", "-M", "main")

    def _create_github_repo(self) -> tuple[str, str]:
        """Create the repo via GitHub REST API. Returns (html_url, clone_url)."""
        headers = {
            "Authorization": f"token {self.github_token}",
            "Accept": "application/vnd.github.v3+json",
        }
        entities = getattr(self, "_spec", {}).get("entities", [])
        entity_names = ", ".join(e["name"] for e in entities) if entities else "API"
        payload = {
            "name": self.repo_name,
            "private": self.private,
            "description": f"{entity_names} REST API — generated by Developable",
            "auto_init": False,
        }
        response = requests.post(
            "https://api.github.com/user/repos",
            headers=headers,
            json=payload,
            timeout=30,
        )

        if response.status_code == 422:
            body = response.json()
            errors = body.get("errors", [])
            if any(e.get("message", "").startswith("name already exists") for e in errors):
                print(
                    f"\nError: Repository '{self.repo_name}' already exists under "
                    f"'{self.github_user}'.\n"
                    "Use --github-repo to choose a different name.",
                    file=sys.stderr,
                )
            else:
                print(f"\nGitHub API error (422): {body}", file=sys.stderr)
            sys.exit(1)

        if not response.ok:
            print(
                f"\nGitHub API error ({response.status_code}): {response.text}",
                file=sys.stderr,
            )
            sys.exit(1)

        data = response.json()
        return data["html_url"], data["clone_url"]

    def _push_to_github(self, clone_url: str) -> None:
        """Push main branch. Embeds token in URL to avoid interactive auth."""
        # Turn https://github.com/user/repo.git
        # into  https://<token>@github.com/user/repo.git
        authed_url = clone_url.replace("https://", f"https://{self.github_token}@")
        self._git("remote", "add", "origin", authed_url)
        try:
            self._git("push", "-u", "origin", "main")
        except subprocess.CalledProcessError as exc:
            print(
                "\nPush failed. You can retry manually:\n"
                f"  cd {self.out_dir}\n"
                "  git push -u origin main",
                file=sys.stderr,
            )
            print(exc.stderr, file=sys.stderr)
            sys.exit(1)

    def _git(self, *args: str) -> str:
        """Run a git command in the output directory."""
        result = subprocess.run(
            ["git", *args],
            cwd=self.out_dir,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise subprocess.CalledProcessError(
                result.returncode, ["git", *args], result.stdout, result.stderr
            )
        return result.stdout
