import subprocess
import sys
import time
from pathlib import Path
from typing import Any

from core.assembler import Assembler
from core.git_client import GitClient
from core.git_identity import GitIdentityResolver
from core.github_client import GitHubClient
from core.gitignore import DEFAULT_GITIGNORE_CONTENT
from core.vc_planner import VCPlanner

_PUSH_MAX_RETRIES = 3
_PUSH_BACKOFF_BASE_S = 2


class VersionControl:
    """
    The Version Control agent.

    Responsible for:
    1. Generating CI/CD infrastructure files (Dockerfile, docker-compose.yml,
       GitHub Actions workflow, .gitignore) into the output directory.
    2. Initialising a git repository and creating an initial commit.
    3. Creating a new GitHub repository via the REST API.
    4. Pushing the main branch to GitHub.

    Follows the same Planner → Assembler pattern as Developer and Tester.

    GitHub credentials are optional when only generate_infra() is needed.
    They are required when publish() is called.
    """

    def __init__(
        self,
        out_dir: Path,
        github_token: str = "",
        github_user: str = "",
        repo_name: str = "",
        private: bool = False,
        project_name: str = "",
    ) -> None:
        self.out_dir = out_dir
        self.github_user = github_user
        self.repo_name = repo_name
        self.private = private
        self.project_name = project_name
        self.assembler = Assembler(out_dir=out_dir, use_llm=False)
        self.git = GitClient(out_dir)
        self.github = GitHubClient(github_token)

    @property
    def github_token(self) -> str:
        return self.github.token

    @github_token.setter
    def github_token(self, value: str) -> None:
        self.github = GitHubClient(value)

    def generate_infra(self, spec: dict[str, Any]) -> dict[str, Any]:
        """Generate infrastructure files and .gitignore — no git or GitHub operations."""
        print("  Generating infrastructure files (Dockerfile, docker-compose, CI)...")
        plan = VCPlanner().plan(spec)
        print(f"  Planned {len(plan['files'])} infrastructure files")
        self.assembler.assemble(spec, plan)
        print("  Writing .gitignore...")
        (self.out_dir / ".gitignore").write_text(DEFAULT_GITIGNORE_CONTENT)
        return plan

    def publish(self, spec: dict[str, Any], api_plan: dict[str, Any]) -> str:
        """
        Init git, create GitHub repo, push.

        generate_infra() must have been called first — infra files must already
        exist in out_dir before this method runs.

        Returns the HTML URL of the created GitHub repository.
        """
        if not self.github.token or not self.github_user or not self.repo_name:
            print(
                "Error: github_token, github_user, and repo_name are required for publish().",
                file=sys.stderr,
            )
            sys.exit(1)

        self._spec = spec
        print("  Initialising git repository...")
        self._init_git()

        print(f"  Creating GitHub repository '{self.github_user}/{self.repo_name}'...")
        repo_html_url, clone_url = self.github.create_repo(
            user=self.github_user,
            name=self.repo_name,
            description=self._repo_description(spec),
            private=self.private,
        )
        self.github.wait_until_accessible(self.github_user, self.repo_name)

        print(f"  Pushing to {repo_html_url} ...")
        self._push_to_github(clone_url)
        return repo_html_url

    # ── Git helpers ────────────────────────────────────────────────────────────

    def _init_git(self) -> None:
        is_new_repo = not (self.out_dir / ".git").exists()
        self.git.run("init")
        GitIdentityResolver(self.git, self.github).resolve()
        self.git.run("add", ".")

        has_staged = subprocess.run(
            ["git", "diff", "--cached", "--quiet"],
            cwd=self.out_dir,
            capture_output=True,
        ).returncode == 1

        if has_staged:
            msg = (
                "Initial commit: Generated by Developable\n\n"
                "API, tests, Dockerfile, docker-compose, and GitHub Actions CI."
                if is_new_repo
                else "Regenerated by Developable"
            )
            self.git.run("commit", "-m", msg)
        if is_new_repo:
            self.git.run("branch", "-M", "main")

    def _repo_description(self, spec: dict[str, Any]) -> str:
        entities = spec.get("entities", [])
        auth = spec.get("auth_entity_name")
        names = [e["name"] for e in entities if e["name"] != auth]
        resource_part = ", ".join(names[:3]) + ("…" if len(names) > 3 else "")
        auth_part = f" · auth via {auth}" if auth else ""
        return f"REST API for {resource_part}{auth_part} — generated by Developable (developablecode.app)"

    def _push_to_github(self, clone_url: str) -> None:
        """Push main branch with retry. Embeds token in URL to avoid interactive auth."""
        authed_url = clone_url.replace("https://", f"https://{self.github.token}@")
        self.git.run("remote", "add", "origin", authed_url)
        delay = _PUSH_BACKOFF_BASE_S
        for attempt in range(1, _PUSH_MAX_RETRIES + 1):
            try:
                self.git.run("push", "-u", "origin", "main")
                return
            except subprocess.CalledProcessError as exc:
                if attempt == _PUSH_MAX_RETRIES:
                    print(
                        "\nPush to GitHub failed after retries.\n"
                        "Common causes:\n"
                        "  1. Token lacks 'repo' scope (classic PAT) or "
                        "Contents:write (fine-grained PAT)\n"
                        f"  2. Verify repo: https://github.com/{self.github_user}/{self.repo_name}\n"
                        "To retry manually:\n"
                        f"  cd {self.out_dir}\n  git push -u origin main",
                        file=sys.stderr,
                    )
                    print(exc.stderr, file=sys.stderr)
                    sys.exit(1)
                print(
                    f"  Push attempt {attempt}/{_PUSH_MAX_RETRIES} failed, "
                    f"retrying in {delay}s...",
                    file=sys.stderr,
                )
                time.sleep(delay)
                delay *= 2
